# Generated by Django 4.2.4 on 2024-01-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('word1', models.CharField(max_length=200)),
                ('word2', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='RequestsFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.BigIntegerField()),
                ('freq', models.IntegerField()),
            ],
            options={
                'db_table': 'request_frequency',
                'ordering': ['-freq'],
            },
        ),
    ]
